---
- name: Install httpd on Webserver group
  hosts: webservers
  become: true
  tasks:
  - name: Install httpd and start the service
    yum:
      name: httpd
      state: installed

  - name: Start httpd service
    service:
      name: httpd
      state: started 
