---
- name: Uninstall httpd on RedHat OS Family
  hosts: all
  become: true
  tasks:
  - name: Stop httpd on RedHat OS Family
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: Uninstall httpd on RedHat OS Family
    yum: 
      name: httpd
      state: removed
    when: ansible_os_family == "RedHat"

  - name: Stop apache2 on Debian OS Family
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: Uninstall apache2 on Debian OS Family
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
