---
# tasks file for setup-apache

- name: Install httpd on RedHat family
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == "RedHat"
  notify: start apache


- name: Install apache2 on Debian family
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: start apache2


- name: Copy index.html to Managed Nodes
  copy:
    src: /opt/ansible/index.html
    dest: /var/www/html
    mode: 0666

- name: Ensure that default apache port is {{ port }}
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen'
    insertafter: '^Listen'
    line: Listen {{ port }}
  when: ansible_os_family == "RedHat"
  notify: restart apache
   
- name: Ensure that default apache2 port is {{ port }}
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen'
    insertafter: "# /etc/apache2/sites-enabled/000-default.conf"
    line: Listen {{ port }}
  when: ansible_os_family == "Debian"
  notify: restart apache2
